# Generated by Django 5.1.2 on 2024-10-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug_alter_factory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=79.9, max_digits=10),
            preserve_default=False,
        ),
    ]
