# Generated by Django 4.2.16 on 2024-12-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='Decor_tiles_1.jpg', null=True, upload_to='products/'),
        ),
    ]
